#!/bin/bash
#name:echolor
#description -- color supported echo

#bashnode::import  echolor

error()
{
  bashnode import echolor
  echolor "<#red>" "$*" "</#red>"
}

warning()
{
  bashnode import echolor
  echolor "<#yellow>" "$*" "</#yellow>"
}


bashnode export error warning
