#!/bin/bash
#name:nodeedit
#description -- helper to create new bashnodes


ed()
{ 
  if [ -f $bashnode_self_path/nodes/$1 ];then 
   vi $bashnode_self_path/nodes/$1
  else 
   tempfile=$(mktemp /tmp/output.XXXXXXXXXX)
   cat $bashnode_self_path/nodes/template >$tempfile

    vi $tempfile
    cmp  $tempfile $bashnode_self_path/nodes/template  2>&1 1>/dev/null && rm $tempfile && return 1
   
    mv $tempfile $bashnode_self_path/nodes/$1 
 
  fi

}

bashnode export  -o nodeedit ed
